[project]
name = 'peer-to-peer-land-rental-network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.condition-validator]
path = 'contracts/condition-validator.clar'
clarity_version = 3
epoch = 'latest'

[contracts.rental-token]
path = 'contracts/rental-token.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
